apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-repo-server
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
