apiVersion: v1
kind: Config

clusters:
  - name: test-cluster
    cluster:
      server: https://172.17.0.2:32165
      insecure-skip-tls-verify: true   # OK for testing only

contexts:
  - name: test-context
    context:
      cluster: test-cluster
      user: test-user

users:
  - name: test-user
    user:
      token: test12345token   # Dummy token for testing

current-context: test-context
